#version 450

#define T int
#define DataType T

layout(std430, binding = 0) buffer Input
{
   DataType inputs[];
};

layout(std430, binding = 1) buffer Output
{
   DataType outputs[];
};

layout (local_size_x = 256) in;

layout(push_constant) uniform PushConsts
{
  int n;
  int stride;
  int offset;
} consts;

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= consts.n) {
        return;
    }
    outputs[idx] = inputs[idx * consts.stride + consts.offset];
}