#version 450
#extension GL_GOOGLE_include_directive : require
#include "../base/Common.glsl"
#include "Interaction.glsl"

layout (local_size_x = 64) in;

layout(std430, binding = 0) buffer B1
{
   int outTriangleIndex[];
};

layout(std430, binding = 1) buffer B2
{
   int outQuadIndex[];
};

layout (push_constant) uniform PushConsts {
	uint num;
} regs;

void main() { 
   uint pId = gl_GlobalInvocationID.x;
   if (pId >= regs.num) return;

   outQuadIndex[pId] = outTriangleIndex[pId * 2] / 2;
}
