#version 450
#extension GL_GOOGLE_include_directive : enable
#include "../math/Quat.glsl"
#include "SharedDataHeightField.glsl"
#extension GL_EXT_debug_printf : enable
layout(std430, binding = 0) buffer Height{
	vec4 height[];
};

layout(binding = 1) buffer Vertex {
	vec3 data[];
};

layout(push_constant) uniform PushConsts
{
  int n;
} consts;

layout (local_size_x = 256) in;

void main(){
	uint index = gl_GlobalInvocationID.x;
	if(index > consts.n) return;
	data[index].y = height[index].x;	
}