#pragma once
#include "PyCommon.h"
#include "PyCore.h"
#include "PyFramework.h"
#include "PyModeling.h"
#include "PyTopology.h"
#include "PyIO.h"
#include "PyObjIO.h"

#include "Rendering/PyRenderCore.h"
#include "Rendering/PyGlfwGUI.h"
#include "Rendering/PyImWidgets.h"
#include "Rendering/PyRendering.h"
#include "Rendering/PyQtGUI.h"

#include "Dynamics/PyDualParticleSystem.h"
#include "Dynamics/PySemiAnalyticalScheme.h"
#include "Dynamics/PyVolume.h"
#include "Dynamics/PyParticleSystem.h"
#include "Dynamics/PyMultiphysics.h"
#include "Dynamics/PyPeridynamics.h"
#include "Dynamics/PyRigidBody.h"
#include "Dynamics/PyHeightField.h"
